from pyspark.sql.types import (
    StructType, StructField, IntegerType, StringType, BooleanType, TimestampType, LongType, DoubleType
)

quiz_objects_schema = StructType([
    StructField("quiz_id", LongType(), False),
    StructField("quiz_name", StringType(), True),
    StructField("quiz_description", StringType(), True),
    StructField("quiz_category", StringType(), True),
    StructField("is_active", BooleanType(), True),
    StructField("org_unit_id", LongType(), False),
    StructField("start_date", TimestampType(), True),
    StructField("end_date", TimestampType(), True),
    StructField("due_date", TimestampType(), True),
    StructField("creation_date", TimestampType(), True),
    StructField("created_by", LongType(), True),
    StructField("last_modified", TimestampType(), True),
    StructField("last_modified_by", LongType(), True),
    StructField("grade_object_id", LongType(), True),
    StructField("overall_score_calculation", StringType(), True),
    StructField("quiz_score_denominator", DoubleType(), True),
    StructField("has_password", BooleanType(), True),
    StructField("ip_restricted", BooleanType(), True),
    StructField("time_limit", IntegerType(), True),
    StructField("time_limit_enforced", BooleanType(), True),
    StructField("attempts_allowed", IntegerType(), True),
    StructField("prevent_moving_backwards", BooleanType(), True),
    StructField("allow_hints", BooleanType(), True),
    StructField("notification_email", StringType(), True),
    StructField("disable_pager_access", BooleanType(), True),
    StructField("display_in_calendar", BooleanType(), True),
    StructField("is_attempt_rldb", BooleanType(), True),
    StructField("is_subview_rldb", BooleanType(), True),
    StructField("sort_order", IntegerType(), True),
    StructField("category_id", LongType(), True),
    StructField("result_id", LongType(), True),
    StructField("is_retake_incorrect_only", BooleanType(), True),
    StructField("paging_type_id", IntegerType(), True),
    StructField("is_synchronous", BooleanType(), True),
    StructField("deduction_percentage", StringType(), True),
    StructField("ai_study_support", BooleanType(), True),
    StructField("hide_question_points", BooleanType(), True),
    StructField("has_quiz_description", BooleanType(), True),
])
